export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_CONTACTS = "GET_CONTACTS";
export const NEW_CONTACT = "NEW_CONTACT";
export const UPDATE_CONTACT = "GET_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";

export const REGISTER_SUCCESS_SAGA = "REGISTER_SUCCESS_SAGA";
export const REGISTER_FAIL_SAGA = "REGISTER_FAIL_SAGA";
export const LOGIN_SUCCESS_SAGA = "LOGIN_SUCCESS_SAGA";
export const LOGIN_FAIL_SAGA = "LOGIN_FAIL_SAGA";
export const LOGOUT_SAGA = "LOGOUT_SAGA";

export const SET_MESSAGE_SAGA = "SET_MESSAGE_SAGA";
export const CLEAR_MESSAGE_SAGA = "CLEAR_MESSAGE_SAGA";

export const GET_CONTACTS_SAGA = "GET_CONTACTS_SAGA";
export const NEW_CONTACT_SAGA = "NEW_CONTACT_SAGA";
export const UPDATE_CONTACT_SAGA = "GET_CONTACT_SAGA";
export const DELETE_CONTACT_SAGA = "DELETE_CONTACT_SAGA";